### ISSUE TITLE
chapter code sort by renewal date doesn't work

### ISSUE THREAD

**Issue by amj** [usgo/agagd#139] opened 2020-11-06 19:52 UTC
## Summary of the Bug
Chapter detail page doesn't sort by renewal date:
https://agagd.usgo.org/chapter/7911/?sort=renewal_due

## Steps to Reproduce the Behaviour
**i.e.,**
1. Go to https://agagd.usgo.org/chapter/7911/?sort=renewal_due
2. Click on the table header to sort by renewal
3. page reloads
4. entries are not sorted

**Comment by vash3g** [comment] 2020-11-06 20:04
This is input as #128 already.

**Comment by vash3g** [comment] 2020-11-07 18:30
Closed as a duplicate of issue #128

**Closed by vash3g** 2020-11-07 18:30 UTC
Labels: bug
